version: 0.0
os: linux
files:
  - source: /leadapp.war
    destination: /home/ubuntu/tomcat7/webapps
hooks:
  BeforeInstall:
      - location: roles/install
        timeout: 300
        runas: root
  ApplicationStop:
    - location: roles/stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: roles/start.sh
      timeout: 300
      runas: root
