version: 0.0
os: linux
files:
  - source: /dest/lib/leadapp.war
    destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
	  runas: ubuntu
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
	  runas: ubuntu
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
    - location: scripts/start_application
      timeout: 300
	  runas: ubuntu
